### ISSUE TITLE
Problems with eval(), Unicode and Python3

### ISSUE THREAD

**Issue by jpuigcerver** [RedTuna/mysolr#13]
Hi!

I found a bug on mysolr 0.5.1. When I tried to perform a simple query to my server, an exception raised on mysolr.py:line 48.

Here is the traceback:

> Traceback (most recent call last):
>  File "solr_test.py", line 4, in <module>
>    response = solr.search(q='_:_',rows=1)
>  File "/usr/local/lib/python3.2/dist-packages/mysolr-0.5.1-py3.2.egg/mysolr/mysolr.py", line 67, in search
>    solr_response = self.__build_response(response)
>  File "/usr/local/lib/python3.2/dist-packages/mysolr-0.5.1-py3.2.egg/mysolr/mysolr.py", line 48, in __build_response
>    response_object = eval(response.content)
>  File "<string>", line 1
>    {'responseHeader':{'status':0,'QTime':0,'params':{'wt':'python','q':'_:_','rows':'1'}},'response':{'numFound':100,'start':0,'maxScore':50.392296,'docs':[{'id':'184335691025625089','user_name':'Microsoft','text':u'RT @bing: We\u2019re joining forces with @bullymovie to help stop bullying in schools. Join us: http://t.co/pSSnht1K','insensitive_text':u'RT @bing: We\u2019re joining forces with @bullymovie to help stop bullying in schools. Join us: http://t.co/pSSnht1K','user_followers':214438,'created_at':'2012-03-26T17:47:08Z','retweet_count':63,'user_nick':'Microsoft','user_statuses':2285,'score':50.392296}]}} 

The problem is that one field of the response has a unicode character and that field is encoded as u'field-text' and Python3 does not know how to interpret that.

Using eval() is not a good practice to parse the JSON response from the server, json.loads() or json.load() should be used instead.

I solved the problem but I have not tested my changes so much. Here is what I've done:
1. Change the value of the 'wt' parameter to 'json' instead of 'python'. The Python response from Solr was designed for Python2, but I am using Python3 and there were problems with the quotation marks. (function mysolr.py:__build_request)
2. Substitute eval() in __build_response(), this is the result:
   def __build_response(self, response):
       """ Build a SolrResponse from http request made with requests. """
       content_str = response.content.decode('utf-8') # Bytes to string
       response_object = json.loads(content_str)
       return SolrResponse(response_object) 

As I said, this is just a quick fix. But I hope that it helps to solve the problem.

Congratulations for this module!

**Comment by moliware** [comment]
Hi,

I think that we're going to change wt parameter to json only for python 3.2. eval makes faster the module ;) and "u" will be supported again in 3.3.

Thanks @jpuigcerver

**Comment by jpuigcerver** [comment]
Hi,

Thanks for your quick reply!
