### ISSUE TITLE
Dependencies Documentation

### ISSUE THREAD

**Issue by fjavieralba** [RedTuna/mysolr#18]
I think we should document the gevent dependency when using async search.

In fact, it's a requests dependency, but if you have not installed gevent, mysolr.async_search will not work.

**Comment by fjavieralba** [comment]
by the way, does gevent support python3?

**Comment by moliware** [comment]
It seems that in the next version of requests, gevent is going to be removed but the author has created 'grequests' for this feature.  So, we have to discuss how to continue supporting async_search.

**Comment by claytron** [comment]
For the new `grequests` package, you can use the `extras_require` from setuptools, documented here:

http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies

Then you can install `mysolr` like this:

```
$ pip install mysolr[async]
```

**Comment by moliware** [comment]
Thanks for the suggestion. I think I'll do it like that.

**Comment by moliware** [comment]
@claytron I included extras_require in this version (0.7.2) but I can't install "mysolr[async]".  Maybe I'm missing something, but using pip 1.2.1 I get this error.

```
✗ pip install mysolr[async]
zsh: no matches found: mysolr[async]
```

**Comment by claytron** [comment]
zsh thinks you are trying to give it a pattern. You need to surround it in double quotes:

```
% pip install "mysolr[async]"
```

Then it should work fine.

**Comment by moliware** [comment]
Thanks again @claytron

**Comment by johnjohndoe** [comment]
@claytron :+1:
