### ISSUE TITLE
Add auth to requests

### ISSUE THREAD

**Issue by pnpnpn** [RedTuna/mysolr#20]
It would be great if there can be an extra parameter 'auth' when making Solr connection:

```
def __init__(self, base_url='http://localhost:8080/solr/', auth=None):
```

Then the requests would use the auth parameter. E.g.

```
def search(self, resource='select', **kwargs):
    query = build_request(kwargs)

    http_response = requests.get(
            urljoin(self.base_url, resource),
            params=query,
            auth=self.auth)
```

The 'auth' parameter would allow for both HTTP Basic Auth and Digest Auth: 

http://docs.python-requests.org/en/latest/user/quickstart/#basic-authentication

**Comment by moliware** [comment]
Thanks for the suggestion. I'll include it in the next version.

**Comment by moliware** [comment]
It is implemented now. It will be included in the next release.
Thanks!!

**Comment by pnpnpn** [comment]
Thank you!

**Comment by moliware** [comment]
Auth feature is in pypi now (v0.7.1). You can check the documentation how to use it: http://mysolr.readthedocs.org/en/latest/user/userguide.html#connecting-to-solr

Thanks
