### ISSUE TITLE
Multiple facets in single request

### ISSUE THREAD

**Issue by miosman** [RedTuna/mysolr#21]
Currently in mysolr 0.7.1 there is no way to define multiple facet fields in the same search request due to the params being a dict and solr dictates that for multiple facet fields you need to define the parameter multiple times (http://wiki.apache.org/solr/SimpleFacetParameters#facet.field)

A solution might to take the params as a list of tuples something along the lines of this:
solr = Solr()
query = [('q' , '_:_'), ('facet' , 'true'), ('facet.field' , 'foo'), ('facet.field' , 'bar')]
response = solr.search(query)

**Comment by almalki** [comment]
this should be easy since requests lib accepts lists of 2 tuples as request params

from requests/models.py

``` python
@staticmethod
    def _encode_params(data):
        """Encode parameters in a piece of data.

Will successfully encode parameters when passed as a dict or a list of
2-tuples. Order is retained if data is a list of 2-tuples but abritrary
if parameters are supplied as a dict.
"""

        if isinstance(data, bytes):
            return data
        if isinstance(data, str):
            return data
        elif hasattr(data, 'read'):
            return data
        elif hasattr(data, '__iter__'):
            try:
                dict(data)
            except ValueError:
                raise ValueError('Unable to encode lists with elements that are not 2-tuples.')

            params = list(data.items() if isinstance(data, dict) else data)
            result = []
            for k, vs in params:
                for v in isinstance(vs, list) and vs or [vs]:
                    result.append(
                        (k.encode('utf-8') if isinstance(k, str) else k,
                         v.encode('utf-8') if isinstance(v, str) else v))
            return urlencode(result, doseq=True)
        else:
            return data

```

**Comment by moliware** [comment]
Hi!

It is supported because you can do something like (as @almalki said):

solr = Solr()
query = {'q' : '_:_', 'facet' : 'true', 'facet.field' : ['foo', 'bar']}
solr.search(**query)

Thanks!
