### ISSUE TITLE
Are the geospatial queries possible?

### ISSUE THREAD

**Issue by dmarko484** [RedTuna/mysolr#22]
Is it possible to use goespatial request with SOLR using mysolr? I mean if I add appropriate params into query as defined in http://wiki.apache.org/solr/SpatialSearch will the response contain correct data? The same question goes to suggester http://wiki.apache.org/solr/Suggester . Will reponse object contain correct seggester section from SOLR response?

**Comment by moliware** [comment]
Yes, it is possible. In the response object you will have a property called raw_content that is the object that sends solr with all the data.

Thanks!
