### ISSUE TITLE
Remove pinning of requests package to specific version

### ISSUE THREAD

**Issue by claytron** [RedTuna/mysolr#23]
Right now, the `requests` version specifier is pinned to `0.12.1` (in a17df4f ). There have been 11 releases since that time. The pinning to a specific version is not making it easy to use this package in a project where the latest requests is in use (I created a fork, just to remove the version pin).

Can this version pinning be removed and left up to the end user to get the proper version if they are using Python 3?

**Comment by moliware** [comment]
I agree with you. I'll remove it. Thanks!

**Comment by moliware** [comment]
Removed! And it's available on pypi http://pypi.python.org/pypi/mysolr/0.7.2

Thanks
