### ISSUE TITLE
mysolr and Apache SOLR 4.0 compatibility issue

### ISSUE THREAD

**Issue by dmarko484** [RedTuna/mysolr#26]
I'm using mysolr with Solr 4.0 RC1, I found just one issue regaring the commit waitFlush parametter that is not used anymore and is reported as uknown attribute by solr and  causing error. 

I fixed this by following (should this be in core?)

a)  added the version param in costructor

``` python
def __init__(self, base_url='http://localhost:8080/solr/', auth=None, version=3):
    self.version=version
```

b) and in commit function do this ...

``` python
if self.version==3:
    xml = '<commit waitFlush="%s" waitSearcher="%s" expungeDeletes="%s" />' % ('true' if wait_flush else 'false',
                                                                                   'true' if wait_searcher else 'false',
                                                                                   'true' if expunge_deletes else 'false')    
else:
    xml = '<commit waitSearcher="%s" expungeDeletes="%s" />' % ('true' if wait_searcher else 'false',
                                                                                   'true' if expunge_deletes else 'false')
```

**Comment by moliware** [comment]
Thanks for reporting it, I will do this change as soon as possible.

I'm working in doing mysolr compatible with 4.0 for the next realese :)

**Comment by moliware** [comment]
I don't know how to handle the version. Maybe it's a good choice passing it as a parameter or maybe we can call /solr/admin/system?wt=json endpoint at init time.

What do you think @rabad, @dmarko484?

**Comment by dmarko484** [comment]
Would prefer parameter, its more clear to me ...

**Comment by rabad** [comment]
I would also vote for the parameter. @moliware, maybe we could also add a flag to the constructor to allow mysolr to retrieve the version?

**Comment by moliware** [comment]
f you agree, we can use a version parameter set to None by default. If we receive the version we use it, if not we retrieve it from the endpoint.

Sounds good?

**Comment by rabad** [comment]
Yep. Let's go for it.

**Comment by dmarko484** [comment]
Yes, nice ...

**Comment by moliware** [comment]
Done
