### ISSUE TITLE
Way to specify timeout for Solr connection

### ISSUE THREAD

**Issue by riteshn-niara** [RedTuna/mysolr#40]
I have been looking at the code but I cannot find a way to specify a timeout for the Solr connection at: https://github.com/RedTuna/mysolr/blob/dev/mysolr/mysolr.py#L26

Am I missing something? Or is this feature not supported?

**Comment by moliware** [comment]
It's not supported yet. 

The ideal way would be something like:

``` python
import requests

session = requests.Session()
session.timeout = 5  # This is not supported as far as I know
solr = Solr('http://localhost:8983/solr/collection1', make_request=session)
```

Maybe I should include a timeout parameter or wait until requests module have something that work like example above. Let me think about it.

Thanks for the suggestion

**Comment by moliware** [comment]
As it was not possible to do it in https://github.com/kennethreitz/requests/pull/2094 we went for a parameter in Solr object (see #42). So if you want to use it download the new version 0.8.3

Thanks
