### ISSUE TITLE
Provide a utility function to convert datetimes into solr-friendly format?

### ISSUE THREAD

**Issue by aravinda0** [RedTuna/mysolr#41]
I'm guessing we can't have auto-handling of datetimes like in pysolr without adding some cruft and a performance hit.
Would it be possible to have a utils module that would provide some helper functions for convenience? ie. converting a datetime to a UTC string.
A simple str(datetimeObj) doesn't work as it's not in the right format for solr. Converting to a UTC string doesn't seem as straightforward as it should in Python.

**Comment by moliware** [comment]
Hi

I agree with you, a utils module is the best way, I will work on it :)

Thanks for the suggestion.

**Comment by moliware** [comment]
I've created a new module, `mysolr.utils`, with a function to convert a datetime to string in iso8601 format. Feel free to add more functions and send them via pull requests :)

Thank you very much
